In [1]:
import numpy as np
import pandas as pd
import os
from sklearn.metrics import mean_squared_error
from math import sqrt

In [35]:
os.listdir()

['test_data.csv',
 'optimizer.pt',
 'Finger print.ipynb',
 'hypersearch-master',
 'split training.zip',
 'QSARs built by deep learning-512-1024.ipynb',
 '654dataset.csv',
 'attachments',
 'params.pt',
 'history.json',
 'generate_RMSE_for_class.ipynb',
 'mdl_wts.hdf5',
 'G2_train_data - group devation.csv',
 'class_RMSE.csv',
 'split training',
 '457dataset.xlsx',
 'manuscrpit-QSAR-jiajie revised-5.17.19.docx',
 'train_data.csv',
 'generate_test_data_from_big_dataset.ipynb',
 'alldata.xlsx',
 'dataset.csv',
 'dataset.xlsx',
 'MLP.ipynb',
 'G2_test_data - group devation.csv',
 'QSARs built by deep learning-2048-1024.ipynb',
 '.ipynb_checkpoints',
 '995dataset.xlsx']

In [36]:
ds = pd.read_csv('G2_train_data - group devation.csv')

In [37]:
ds.head()

         Contaminants_name      smiles_parents     LogKOH    class    PLogKOH
0  1,2,4-trihydroxybenzene  OC1=C(C=C(C=C1)O)O   9.934498  benzene   9.975266
1          2-methoxyphenol    COC1=C(C=CC=C1)O  10.301030  benzene  10.249686
2              3-pentanone           CCC(CC)=O   9.146128   ketone   9.063180
3       1,2-Dibromobenzene   BrC1=C(C=CC=C1)Br   9.361728  benzene   9.358095
4               1-Pentanol            C(CCCC)O   9.591065  alcohol   9.621839

In [10]:
set(ds['class'])

{'alcohol',
 'aldehyde',
 'alkane',
 'alkene',
 'amide',
 'amine',
 'benzene',
 'carboxyl',
 'cyclo',
 'dicarboxylic',
 'diol',
 'ester',
 'ether',
 'furan',
 'halogeneted',
 'imidazole',
 'ketone',
 'nitrile',
 'nitro',
 'nitroso, nitramine',
 'phosphorus',
 'pyridine',
 'sulfide, disulfide',
 'sulfoxide',
 'thiol',
 'triazine',
 'urea'}

In [38]:
len(set(ds['class']))

27

In [39]:
ds_class = pd.DataFrame(list(set(ds['class'])), columns=['Class'])

In [40]:
ds_class

                 Class
0            imidazole
1             triazine
2                furan
3             aldehyde
4               alkane
5                thiol
6             carboxyl
7              alcohol
8   sulfide, disulfide
9   nitroso, nitramine
10               cyclo
11         halogeneted
12                diol
13               amine
14               amide
15              ketone
16                urea
17           sulfoxide
18          phosphorus
19            pyridine
20              alkene
21               nitro
22               ester
23             benzene
24        dicarboxylic
25               ether
26             nitrile

In [42]:
a = []
b = []
for i in set(ds['class']):
    temp = ds[ds['class'] == i]
    n = len(temp)
    rmse = sqrt(mean_squared_error(temp.LogKOH, temp.PLogKOH))
    a.append(rmse)
    b.append(n)

In [43]:
ds_class['RMSE'] = a
ds_class['Num'] = b

In [44]:
ds_class

                 Class      RMSE  Num
0            imidazole  0.081729   13
1             triazine  0.072690   14
2                furan  0.076211    5
3             aldehyde  0.077063    7
4               alkane  0.121997   10
5                thiol  0.160979    3
6             carboxyl  0.077417    8
7              alcohol  0.072106   14
8   sulfide, disulfide  0.149356    6
9   nitroso, nitramine  0.049769   10
10               cyclo  0.237506   14
11         halogeneted  0.232561   22
12                diol  0.062112   10
13               amine  0.139643   18
14               amide  0.064544   12
15              ketone  0.206487    6
16                urea  0.078479    4
17           sulfoxide  0.120751    6
18          phosphorus  0.133773    4
19            pyridine  0.056475   15
20              alkene  0.163435   22
21               nitro  0.187553    6
22               ester  0.060295    6
23             benzene  0.069226  105
24        dicarboxylic  0.181247    9
25               ether  0.131066   13
26             nitrile  0.503960    3

In [45]:
ds_class.to_csv('class_RMSE.csv', index = False)